services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 9090:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/app

  php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
      args:
        - USER=1000
        - GROUP=1000
    container_name: php-dev
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/app
